### ISSUE TITLE
Link to Voxel-level data is broken or non-existing

### ISSUE THREAD

**Issue by GGonEsc** [sidchop/neuRo-vis-BrainHack-2021#1]
The link provided to Voxel-level data:
https://github.com/sidchop/neuRo-vis-BrainHack-2021/blob/main/nifti.Rmd
returns a 404 not found error.
Of course, the problem is that there is no blob folder on the repo.

**Comment by sidchop** [comment]
thanks for pointing this out. Looks like I forgot to update the link when I renamed from nifti.rmd to voxel.rmd. Should be fixed now.
